# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'KakePrototype' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KakePrototype

pod 'RealmSwift'

  target 'KakePrototypeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KakePrototypeUITests' do
    # Pods for testing
  end

end
